issuer: http://dex.local/dex

storage:
  type: sqlite3
  config:
    file: /tmp/dex.db

web:
  http: 0.0.0.0:5556

staticClients:
  - id: grafana
    redirectURIs:
      - "http://grafana.local/login/generic_oauth"
    name: Grafana
    secret: grafana_secret
  - id: forgejo
    redirectURIs:
      - "http://forgejo.local/user/oauth2/dex/callback"
    name: Forgejo
    secret: forgejo_secret

enablePasswordDB: true
staticPasswords:
  - email: "admin@local"
    hash: "$2b$10$V.p1duzRnz88aCVOUn2aEuWew.qmnHN42SOyzulJcVxYWqBaVO7oy"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466" 